name: chess-opening-analyzer-transform-data
services:
  python:
    build: .
    command: sh -c "python3 csv_to_mongo.py && sleep 30"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MONGO_URI=${MONGO_URI}
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - default
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default

volumes:
  mongo-data:
  
networks:
  default:
    driver: bridge